#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  9 09:45:33 2022

@author: tom
"""

import random
import numpy as np

#for row in number_grid: 
   # print(row)
   
def create_random_matrix(rows, columns):
    print(np.floor(np.random.randint(rows, columns)))
    
#def create_random_matrix_ints(rows, columns):
    #print([[round(random.random()*10, 0) for _ in range(rows)] for _ in range(columns)])

# =============================================================================
# def create_rand_grid(rows, columns):
#     number_grid = [[0] * rows]*columns
#     
#     for row in range(rows):
#         for col in range(columns):
#              number_grid[row][col] = int(np.floor((random.random()*10)))
#              print(f'(i = {row} and j = {col})')
# 
#              print(number_grid[row][col])
#     
#     for u in range(0, rows):
#         print(number_grid[u])
#     return number_grid
# =============================================================================


#create_rand_grid(5, 5)
create_random_matrix(5, 5)
#create_random_matrix_ints(5, 5)
#print(int(np.floor((random.random()*10))))